---
fortune:
  dailynumber: 2
  message:
        - Determination is the wake-up call to the human will.
        - TL;DR
        - The Wheel of Good Fortune is finally turning in your direction!
        - "Analysis" is "design" spelled backwards.
        - Captain Clark welcomes you aboard.
        - Caught in --More-- loop.
        - If you cannot convince them, confuse them.  -Harry S. Truman
        - Secret mail has arrived.
        - Computer Science is no more about computers than astronomy is about telescopes
        - Have an adequate day.
        - Life is just sudden-death overtime.
